name = "strengthcalc"
version = "0.1.3"
license = "MIT"
author = "Piotr Bajdek"
maintainer = "piotr.bajdek@proton.me"
copyright = "Copyright 2022, Piotr Bajdek"
[build]
auto-executables = true
auto-tests = true
auto-examples = true
[install]
library = false
